//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CarRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rentals()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int RentalId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CarId { get; set; }
        public string CalculationType { get; set; }
        public System.DateTime DataFrom { get; set; }
        public Nullable<System.DateTime> DataTo { get; set; }
    
        public virtual Cars Cars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Users Users { get; set; }
    }
}
