//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_CarRentals
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sharing
    {
        public int SharingId { get; set; }
        public Nullable<int> CarId { get; set; }
        public System.DateTime DataFrom { get; set; }
        public Nullable<System.DateTime> DataTo { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
