CREATE TABLE Users(
	UserId INT IDENTITY PRIMARY KEY,
	Login NVARCHAR(30) NOT NULL,
	Password NVARCHAR(30) NOT NULL,
	Name NVARCHAR(30) NOT NULL,
	LastName NVARCHAR(30) NOT NULL,
	DateOfBirth DATE NOT NULL,
	City NVARCHAR(30) NOT NULL,
	Phone CHAR(9)  NOT NULL,
	Email NVARCHAR(45) UNIQUE  NOT NULL,
	PESEL CHAR(11) UNIQUE  NOT NULL
)


CREATE TABLE Cars(
	CarId INT IDENTITY PRIMARY KEY,
	Brand NVARCHAR(30) NOT NULL,
	Model NVARCHAR(30) NOT NULL, 
	Type NVARCHAR(30) NOT NULL, 
	CarYear INT NOT NULL,
	FuelType NVARCHAR(30) NOT NULL, 
	Mileage INT NOT NULL,
	Availability NVARCHAR(30) NOT NULL, 
	PricePerKm DECIMAL(18,2) NOT NULL,
	PricePerHour DECIMAL(18,2) NOT NULL,
	PricePerDay DECIMAL(18,2) NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId)
)

CREATE TABLE Rentals(
	RentalId INT IDENTITY PRIMARY KEY,
	UserId INT FOREIGN KEY REFERENCES Users(UserId),
	CarId INT FOREIGN KEY REFERENCES Cars(CarId),
	CalculationType NVARCHAR(30) NOT NULL,
	DataFrom DATE NOT NULL,
	DataTo DATE 
)

CREATE TABLE Sharing(
	SharingId INT IDENTITY PRIMARY KEY,
	CarId INT FOREIGN KEY REFERENCES Cars(CarId),
	DataFrom DATE NOT NULL,
	DataTo DATE 
)

CREATE TABLE Payments(
	PaymentID INT IDENTITY PRIMARY KEY,
	TotalAmount DECIMAL(18,2)  NOT NULL,
	UserId INT FOREIGN KEY REFERENCES Users(UserId),
	RentalId INT FOREIGN KEY REFERENCES Rentals(RentalId)
)